version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/api
      - ./src:/api/src
    command: bash -c "go run src/main.go"